#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
cd $SCRIPT_DIR

docker run -it \
	--name dwg-php8cli \
	--network=dwg \
	--env-file .env \
	--env-file ip.env \
	--rm \
	-v "./site/":/site \
	--link dbpostgres \
	--link dbmaria
	-w /site \
	treehousetim/php-cli-pdo:8.0 \
	php $@
