#!/bin/bash
docker stop dwg-nginx
docker stop dwg-php
docker stop dbmaria
docker stop dbpostgres
docker stop dnsmasq
docker stop dwg-php8cli
docker stop dwg-php8cli2

docker rm dwg-nginx
docker rm dwg-php
docker rm dbmaria
docker rm dbpostgres
docker rm phpcli
docker rm dwg-php8cli
docker rm dwg-php8cli2