#!/bin/bash
./sh/env-copy
docker run -it \
	--name phpexec \
	--network=dwg \
	--env-file .env \
	--env-file .ip.env \
	--rm \
	-v "./site/":/site \
	--link dbpostgres \
	--link dbmaria
	-w /site \
	treehousetim/php-cli-pdo:8.0 \
	php $1
